// Text-only layouts retain the user's photo; every caption remains editable.
export const xhsLayouts = [
  {
    id: "xhs-outline",
    name: "大字描边",
    layers: [
      {
        text: "这个家\n太会装了",
        fontSize: 196,
        fontWeight: 900,
        x: 0.08,
        y: 0.09,
        stroke: 7,
        shadow: true,
      },
      {
        text: " 把普通日子，住成喜欢的样子 ",
        fontSize: 40,
        fontWeight: 600,
        x: 0.085,
        y: 0.43,
        color: "#202124",
        textBackground: "#F5DF4D",
      },
    ],
  },
  {
    id: "xhs-highlight",
    name: "荧光重点",
    layers: [
      {
        text: " 空间改造灵感 ",
        fontSize: 34,
        fontWeight: 600,
        x: 0.085,
        y: 0.065,
        textBackground: "#202124",
      },
      {
        text: " 小户型 ",
        fontSize: 174,
        fontWeight: 900,
        x: 0.08,
        y: 0.135,
        color: "#202124",
        textBackground: "#F5DF4D",
        rotation: -3,
      },
      {
        text: " 也能显大 ",
        fontSize: 174,
        fontWeight: 900,
        x: 0.08,
        y: 0.29,
        color: "#202124",
        textBackground: "#F5DF4D",
        rotation: -3,
      },
      {
        text: "布局 / 采光 / 收纳",
        fontSize: 42,
        x: 0.1,
        y: 0.48,
        shadow: true,
      },
    ],
  },
  {
    id: "xhs-checklist",
    name: "数字清单",
    layers: [
      {
        text: "05",
        fontSize: 248,
        fontWeight: 900,
        x: 0.06,
        y: 0.045,
        color: "#F5DF4D",
        stroke: 3,
      },
      {
        text: "个让家\n变好看的细节",
        fontSize: 86,
        fontWeight: 700,
        x: 0.37,
        y: 0.09,
        shadow: true,
      },
      {
        text: " 01  留白，比堆满更重要 ",
        fontSize: 48,
        fontWeight: 600,
        x: 0.085,
        y: 0.43,
        color: "#202124",
        textBackground: "#FFFFFF",
      },
      {
        text: " 02  灯光，决定空间情绪 ",
        fontSize: 48,
        fontWeight: 600,
        x: 0.085,
        y: 0.5,
        color: "#202124",
        textBackground: "#FFFFFF",
      },
      {
        text: " 03  材质，尽量做减法 ",
        fontSize: 48,
        fontWeight: 600,
        x: 0.085,
        y: 0.57,
        color: "#202124",
        textBackground: "#FFFFFF",
      },
      {
        text: "收藏这份家居灵感清单",
        fontSize: 34,
        x: 0.09,
        y: 0.87,
        shadow: true,
      },
    ],
  },
  {
    id: "xhs-magazine",
    name: "杂志大刊",
    fontFamily: "Noto Serif SC Variable",
    layers: [
      { text: "LIVING", fontSize: 188, fontWeight: 600, x: 0.08, y: 0.055 },
      {
        text: "家居特辑  /  VOL. 01",
        fontSize: 28,
        fontWeight: 400,
        x: 0.095,
        y: 0.205,
      },
      {
        text: "理想生活\n有了形状",
        fontSize: 112,
        fontWeight: 500,
        x: 0.085,
        y: 0.66,
        shadow: true,
      },
      {
        text: "A PLACE TO CALL HOME",
        fontSize: 24,
        fontWeight: 400,
        x: 0.095,
        y: 0.865,
      },
    ],
  },
  {
    id: "xhs-minimal",
    name: "留白氛围",
    layers: [
      { text: "S P A C E", fontSize: 28, fontWeight: 300, x: 0.1, y: 0.075 },
      {
        text: "让家，慢下来",
        fontSize: 70,
        fontWeight: 300,
        x: 0.095,
        y: 0.77,
        shadow: true,
      },
      {
        text: "一间房子，一种生活节奏",
        fontSize: 26,
        fontWeight: 400,
        x: 0.1,
        y: 0.85,
        shadow: true,
      },
    ],
  },
  {
    id: "xhs-compare",
    name: "双栏对比",
    layers: [
      {
        text: "同一个家\n两种生活",
        fontSize: 148,
        fontWeight: 800,
        x: 0.085,
        y: 0.075,
        stroke: 3,
      },
      {
        text: " 改造前 ",
        fontSize: 64,
        fontWeight: 800,
        x: 0.085,
        y: 0.665,
        color: "#202124",
        textBackground: "#FFFFFF",
      },
      {
        text: " 改造后 ",
        fontSize: 64,
        fontWeight: 800,
        x: 0.56,
        y: 0.665,
        color: "#202124",
        textBackground: "#F5DF4D",
      },
      {
        text: "BEFORE",
        fontSize: 26,
        fontWeight: 500,
        x: 0.12,
        y: 0.735,
        shadow: true,
      },
      {
        text: "AFTER",
        fontSize: 26,
        fontWeight: 500,
        x: 0.6,
        y: 0.735,
        shadow: true,
      },
      {
        text: "改变布局，也改变日常",
        fontSize: 34,
        x: 0.09,
        y: 0.875,
        shadow: true,
      },
    ],
  },
  {
    id: "xhs-question",
    name: "提问悬念",
    layers: [
      {
        text: "为什么",
        fontSize: 150,
        fontWeight: 600,
        x: 0.085,
        y: 0.08,
        stroke: 3,
      },
      {
        text: "你家显小？",
        fontSize: 168,
        fontWeight: 900,
        x: 0.075,
        y: 0.23,
        stroke: 7,
      },
      {
        text: " 可能不是面积的问题 ",
        fontSize: 52,
        fontWeight: 800,
        x: 0.09,
        y: 0.41,
        color: "#FFFFFF",
        textBackground: "#C7333D",
      },
      {
        text: "从这 3 个地方找答案",
        fontSize: 38,
        x: 0.1,
        y: 0.875,
        shadow: true,
      },
    ],
  },
  {
    id: "xhs-notes",
    name: "便签干货",
    layers: [
      {
        text: " 装修避坑笔记 ",
        fontSize: 106,
        fontWeight: 800,
        x: 0.07,
        y: 0.09,
        color: "#202124",
        textBackground: "#FFFFFF",
      },
      {
        text: " 开工前，先想清楚这些事 ",
        fontSize: 42,
        fontWeight: 500,
        x: 0.075,
        y: 0.205,
        color: "#C7333D",
        textBackground: "#FFFFFF",
      },
      {
        text: " 01  先定生活习惯，再定风格 ",
        fontSize: 46,
        fontWeight: 600,
        x: 0.08,
        y: 0.37,
        color: "#202124",
        textBackground: "#FFFFFF",
      },
      {
        text: " 02  先留预算，再挑材料 ",
        fontSize: 46,
        fontWeight: 600,
        x: 0.08,
        y: 0.45,
        color: "#202124",
        textBackground: "#FFFFFF",
      },
      {
        text: " 03  先看动线，再谈收纳 ",
        fontSize: 46,
        fontWeight: 600,
        x: 0.08,
        y: 0.53,
        color: "#202124",
        textBackground: "#FFFFFF",
      },
      {
        text: " 实用经验 / 持续更新 ",
        fontSize: 28,
        x: 0.09,
        y: 0.88,
        color: "#202124",
        textBackground: "#F5DF4D",
      },
    ],
  },
  {
    id: "xhs-plog",
    name: "胶片日记",
    layers: [
      { text: "PLOG", fontSize: 206, fontWeight: 300, x: 0.075, y: 0.05 },
      {
        text: "2026 / 09     WEEKEND",
        fontSize: 28,
        fontWeight: 400,
        x: 0.085,
        y: 0.215,
      },
      {
        text: "关于家的\n一些小美好",
        fontSize: 94,
        fontFamily: "Noto Serif SC Variable",
        fontWeight: 400,
        x: 0.09,
        y: 0.68,
        shadow: true,
      },
      {
        text: "LIFE IN LITTLE MOMENTS",
        fontSize: 22,
        x: 0.095,
        y: 0.89,
        shadow: true,
      },
    ],
  },
  {
    id: "xhs-stickers",
    name: "贴纸批注",
    layers: [
      {
        text: " 这才是 ",
        fontSize: 130,
        fontWeight: 900,
        x: 0.08,
        y: 0.1,
        color: "#202124",
        textBackground: "#FFFFFF",
        rotation: -6,
      },
      {
        text: " 我想要的家 ",
        fontSize: 132,
        fontWeight: 900,
        x: 0.13,
        y: 0.245,
        color: "#202124",
        textBackground: "#F5DF4D",
        rotation: 3,
      },
      {
        text: " 自然光，刚刚好 ",
        fontSize: 42,
        fontWeight: 600,
        x: 0.08,
        y: 0.59,
        color: "#202124",
        textBackground: "#FFFFFF",
        rotation: -4,
      },
      {
        text: " 把舒适放在第一位 ",
        fontSize: 42,
        fontWeight: 600,
        x: 0.45,
        y: 0.8,
        color: "#FFFFFF",
        textBackground: "#0F4C81",
        rotation: 3,
      },
    ],
  },
];
